FROM almalinux
RUN dnf install nginx -y
RUN rm -rf /usr/share/nginx/html/index.html
ADD https://raw.githubusercontent.com/venugopal8878/devops-practice/refs/heads/main/understanding%20text  /usr/share/nginx/html/index.html
CMD ["nginx", "-g","daemon off;"]